server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/positions.yaml

clients:
  - url: http://loki_container:3100/loki/api/v1/push

scrape_configs:
- job_name: containers
  static_configs:
    - targets:
        - localhost
      labels:
        job: containers
        __path__: /var/lib/docker/containers/*/*-json.log
  pipeline_stages:
    - json:
        expressions:
          output: log
    # - logfmt:
    #     source: output
