api:
  enabled: true
  address: "0.0.0.0:8686"
  playground: false

sources:
  docker_logs:
    type: "docker_logs"
    docker_host: "unix:///var/run/docker.sock"
    include_containers: ["*"]
    exclude_containers: ["vector_container", "loki_container"]
    include_images: ["*"]
    auto_partial_merge: true

transforms:
  parse_docker_logs:
    type: "remap"
    inputs: ["docker_logs"]
    source: |
      # Parse Docker's JSON log format
      if exists(.log) {
        parsed = parse_json!(.log)
        if exists(parsed.log) {
          .message = parsed.log
          .stream = parsed.stream
          .time = parsed.time
        } else {
          .message = .log
        }
      }
      
      # Add container metadata
      .container_name = .container_name
      .container_id = .container_id
      .image = .image
      .source = "docker"

sinks:
  console:
    type: "console"
    inputs: ["parse_docker_logs"]
    encoding:
      codec: "json"
  
  # Structured JSON logs for Grafana integration
  json_logs:
    type: "file"
    inputs: ["parse_docker_logs"]
    path: "/var/log/vector/container-logs.json"
    encoding:
      codec: "json"
    compression: "gzip"
    buffer:
      type: "disk"
      max_size: 268435488
      when_full: "block"
  
  # Plain text logs for easy reading
  text_logs:
    type: "file"
    inputs: ["parse_docker_logs"]
    path: "/var/log/vector/container-logs.txt"
    encoding:
      codec: "text"
      timestamp_format: "rfc3339"
    buffer:
      type: "disk"
      max_size: 268435488
      when_full: "block" 