server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promtail/positions.yaml

clients:
  - url: http://loki_container:3100/loki/api/v1/push

scrape_configs:
- job_name: containers
  static_configs:
    - targets:
        - localhost
      labels:
        job: containers
        __path__: /var/lib/docker/containers/*/*-json.log
  pipeline_stages:
    - json:
        expressions:
          output: log
    # - logfmt:
    #     source: output
- job_name: docker-service-discovery
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
  relabel_configs:
    - source_labels: ['__meta_docker_container_label_loki_job_name']
      action: keep
      regex: .+
    - source_labels: ['__meta_docker_container_label_loki_job_name']
      target_label: 'job'
