server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promtail/positions.yaml

clients:
  - url: http://loki_container:3100/loki/api/v1/push

scrape_configs:
- job_name: containers
  static_configs:
    - targets:
        - localhost
      labels:
        job: containers
        __path__: /var/lib/docker/containers/*/*-json.log
  relabel_configs:
    - source_labels: ['__path__']
      regex: '/var/lib/docker/containers/([a-f0-9]{64})/.*'
      target_label: 'container_id'
    - source_labels: ['__path__']
      regex: '/var/lib/docker/containers/[a-f0-9]{64}/([a-f0-9]{64})-json\.log'
      target_label: 'container_name'
  pipeline_stages:
    # Extract and clean the log content
    - json:
        expressions:
          log: log
          stream: stream
          time: time
    # Replace escaped quotes to prevent metadata parsing issues
    - replace:
        expression: '\\"'
        replace: '"'
        source: log
